### ISSUE TITLE
No module named 'detectron2.modeling.roi_heads.mask_head_from_SSP'

### ISSUE THREAD

**Issue by Chan-Sun** [DeepDoNet/DoNet#10]
Hi! Thanks for your excellent work. 

But when implementing your code, I found several files are missing. 

The errors are shown below.
```
Traceback (most recent call last):
  File "/workspace/DoNet/customized_tools/train.py", line 2, in <module>
    from detectron2 import model_zoo
  File "/opt/conda/lib/python3.7/site-packages/detectron2/model_zoo/__init__.py", line 7, in <module>
    from .model_zoo import get, get_config_file, get_checkpoint_url
  File "/opt/conda/lib/python3.7/site-packages/detectron2/model_zoo/model_zoo.py", line 8, in <module>
    from detectron2.modeling import build_model
  File "/opt/conda/lib/python3.7/site-packages/detectron2/modeling/__init__.py", line 17, in <module>
    from .meta_arch import (
  File "/opt/conda/lib/python3.7/site-packages/detectron2/modeling/meta_arch/__init__.py", line 6, in <module>
    from .panoptic_fpn import PanopticFPN
  File "/opt/conda/lib/python3.7/site-packages/detectron2/modeling/meta_arch/panoptic_fpn.py", line 12, in <module>
    from ..roi_heads import build_roi_heads
  File "/opt/conda/lib/python3.7/site-packages/detectron2/modeling/roi_heads/__init__.py", line 5, in <module>
    from .roi_heads import (
  File "/opt/conda/lib/python3.7/site-packages/detectron2/modeling/roi_heads/roi_heads.py", line 35, in <module>
    from .mask_head_from_SSP import build_mask_head_from_SSP,mask_rcnn_inference, amodal_mask_rcnn_inference,\
ModuleNotFoundError: No module named 'detectron2.modeling.roi_heads.mask_head_from_SSP'
```

It looks like the `mask_head_from_SSP` and `recon_net` modules are missing. Could you fix this issue?

Many thanks

**Comment by rzhangbq** [comment]
See #15
