### ISSUE TITLE
ModuleNotFoundError:

### ISSUE THREAD

**Issue by owtn** [DeepDoNet/DoNet#13]
Hello, thanks for your work.
But it looks like the mask_head_from_SSP and recon_net modules are missing.
`Traceback (most recent call last):
  File "customized_tools/train.py", line 2, in <module>
    from detectron2 import model_zoo
  File "/home/hdd2/zhangjinyu/anaconda3/envs/general/lib/python3.7/site-packages/detectron2-0.1-py3.7-linux-x86_64.egg/detectron2/model_zoo/__init__.py", line 7, in <module>
    from .model_zoo import get, get_config_file, get_checkpoint_url
  File "/home/hdd2/zhangjinyu/anaconda3/envs/general/lib/python3.7/site-packages/detectron2-0.1-py3.7-linux-x86_64.egg/detectron2/model_zoo/model_zoo.py", line 8, in <module>
    from detectron2.modeling import build_model
  File "/home/hdd2/zhangjinyu/anaconda3/envs/general/lib/python3.7/site-packages/detectron2-0.1-py3.7-linux-x86_64.egg/detectron2/modeling/__init__.py", line 17, in <module>
    from .meta_arch import (
  File "/home/hdd2/zhangjinyu/anaconda3/envs/general/lib/python3.7/site-packages/detectron2-0.1-py3.7-linux-x86_64.egg/detectron2/modeling/meta_arch/__init__.py", line 6, in <module>
    from .panoptic_fpn import PanopticFPN
  File "/home/hdd2/zhangjinyu/anaconda3/envs/general/lib/python3.7/site-packages/detectron2-0.1-py3.7-linux-x86_64.egg/detectron2/modeling/meta_arch/panoptic_fpn.py", line 12, in <module>
    from ..roi_heads import build_roi_heads
  File "/home/hdd2/zhangjinyu/anaconda3/envs/general/lib/python3.7/site-packages/detectron2-0.1-py3.7-linux-x86_64.egg/detectron2/modeling/roi_heads/__init__.py", line 5, in <module>
    from .roi_heads import (
  File "/home/hdd2/zhangjinyu/anaconda3/envs/general/lib/python3.7/site-packages/detectron2-0.1-py3.7-linux-x86_64.egg/detectron2/modeling/roi_heads/roi_heads.py", line 38, in <module>
    from .recon_net import build_reconstruction_head, mask_recon_loss, mask_recon_inference
ModuleNotFoundError: No module named 'detectron2.modeling.roi_heads.recon_net'`
`Traceback (most recent call last):
  File "customized_tools/train.py", line 2, in &lt;module&gt;
    from detectron2 import model_zoo
  File "/home/hdd2/zhangjinyu/anaconda3/envs/general/lib/python3.7/site-packages/detectron2-0.1-py3.7-linux-x86_64.egg/detectron2/model_zoo/__init__.py", line 7, in &lt;module&gt;
    from .model_zoo import get, get_config_file, get_checkpoint_url
  File "/home/hdd2/zhangjinyu/anaconda3/envs/general/lib/python3.7/site-packages/detectron2-0.1-py3.7-linux-x86_64.egg/detectron2/model_zoo/model_zoo.py", line 8, in &lt;module&gt;
    from detectron2.modeling import build_model
  File "/home/hdd2/zhangjinyu/anaconda3/envs/general/lib/python3.7/site-packages/detectron2-0.1-py3.7-linux-x86_64.egg/detectron2/modeling/__init__.py", line 17, in &lt;module&gt;
    from .meta_arch import (
  File "/home/hdd2/zhangjinyu/anaconda3/envs/general/lib/python3.7/site-packages/detectron2-0.1-py3.7-linux-x86_64.egg/detectron2/modeling/meta_arch/__init__.py", line 6, in &lt;module&gt;
    from .panoptic_fpn import PanopticFPN
  File "/home/hdd2/zhangjinyu/anaconda3/envs/general/lib/python3.7/site-packages/detectron2-0.1-py3.7-linux-x86_64.egg/detectron2/modeling/meta_arch/panoptic_fpn.py", line 12, in &lt;module&gt;
    from ..roi_heads import build_roi_heads
  File "/home/hdd2/zhangjinyu/anaconda3/envs/general/lib/python3.7/site-packages/detectron2-0.1-py3.7-linux-x86_64.egg/detectron2/modeling/roi_heads/__init__.py", line 5, in &lt;module&gt;
    from .roi_heads import (
  File "/home/hdd2/zhangjinyu/anaconda3/envs/general/lib/python3.7/site-packages/detectron2-0.1-py3.7-linux-x86_64.egg/detectron2/modeling/roi_heads/roi_heads.py", line 35, in &lt;module&gt;
    from .mask_head_from_SSP import build_mask_head_from_SSP,mask_rcnn_inference, amodal_mask_rcnn_inference,\
ModuleNotFoundError: No module named 'detectron2.modeling.roi_heads.mask_head_from_SSP'`

**Comment by rzhangbq** [comment]
See https://github.com/DeepDoNet/DoNet/issues/15
